import { FilterContextProvider } from "@/Context";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <FilterContextProvider>
          <Header />
          {children}
          <Footer />
        </FilterContextProvider>
      </body>
    </html>
  );
}
